### ISSUE TITLE
Canceled due to missing image file path

### ISSUE THREAD

**Issue by loooog** [hahnec/depthy#3]
Hi, I got that result message while running command:

`depthy -s './examples/data/pens/'`

Was I using the wrong method?

**Comment by hahnec** [comment]
Hi, the above command runs fine when cloning the repo on my machine. Have you installed the tool via package manager pip? The examples folder is not shipped in the pip distribution and has to be added manually. So, either you clone the repo or download the files manually. The links for download can be found in the README file. Hope this works for you.

**Comment by loooog** [comment]
> Hi, the above command runs fine when cloning the repo on my machine. Have you installed the tool via package manager pip? The examples folder is not shipped in the pip distribution and has to be added manually. So, either you clone the repo or download the files manually. The links for download can be found in the README file. Hope this works for you.

Hi, Yes I have clone the repository and also tried to copy sample images to example folder.
`    depthy -s './examples/data/pens/'
`

If I run this command with -s option following by a image folder, I got

```
Downloads/min/depthy/depthy/misc/io_functions.py", line 53, in <lambda>
    fnames = sorted(fnames, key=lambda x: int(re.sub("[^0-9]", "", os.path.basename(x).split(".")[0])))
ValueError: invalid literal for int() with base 10: ''
```

error message.

**Comment by hahnec** [comment]
Can you confirm you are executing the above depthy command from a directory where the examples folder resides?

**Comment by loooog** [comment]
> Can you confirm you are executing the above depthy command from a directory where the examples folder resides?


Hi, Yes. This is the root folder where I run the command:

![image](https://user-images.githubusercontent.com/5425520/150268450-35d66f0b-d213-428e-9eba-6f58de62c67d.png)

And this is the content of the example folder:
![image](https://user-images.githubusercontent.com/5425520/150270240-3fab601b-a0c4-470b-ae70-d726ed256310.png)


.
